apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-cluster-role-devops
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets","configmaps","endpoints","nodes","services","namespaces","events","serviceaccounts"]
  verbs: ["get", "watch", "list","create","patch","update"]